# Generated by Django 3.1 on 2024-01-19 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFinder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.CharField(max_length=255)),
                ('amazon', models.FileField(upload_to='amazon/')),
                ('flipkart', models.FileField(upload_to='flipkart/')),
                ('walmart', models.FileField(upload_to='walmart/')),
            ],
        ),
    ]
