# Generated by Django 3.1 on 2024-01-19 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apkakart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfinder',
            name='amazon',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='productfinder',
            name='flipkart',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='productfinder',
            name='walmart',
            field=models.TextField(),
        ),
    ]
