import React, { useRef, useEffect } from "react";
import VANTA from "vanta";
import * as THREE from "three";
import Typewriter from 'typewriter-effect';
import "../Style/background.css";
const Background = () => {
  
    const downloadFile = () => {
      window.location.href = "https://yoursite.com/src/assets/files/exampleDoc.pdf"
    }
  return (
    <div className="background">
      <div className="text_back">
        <Typewriter
  options={{
    strings: ['Welcome', 'To', "Apna mart"],
    autoStart: true,
    loop: true,
  }}
/>
<button class="btn" target="_blank" onClick={downloadFile} >User flow</button>
</div>
      <div class="container">
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="trigger"></div>
        <div class="monitor">
          <div class="camera o-x">
            <div class="camera o-y">
              <div class="camera o-z">
                <div class="vr">
                  <div class="vr_layer">
                    <div class="vr_layer_item"></div>
                  </div>
                  <div class="vr_layer">
                    <div class="vr_layer_item"></div>
                  </div>
                  <div class="vr_layer">
                    <div class="vr_layer_item"></div>
                  </div>
                  <div class="vr_layer">
                    <div class="vr_layer_item"></div>
                  </div>
                  <div class="vr_layer">
                    <div class="vr_layer_item"></div>
                  </div>
                  <div class="vr_layer">
                    <div class="vr_layer_item"></div>
                  </div>
                  <div class="vr_layer">
                    <div class="vr_layer_item"></div>
                  </div>
                  <div class="vr_layer">
                    <div class="vr_layer_item"></div>
                  </div>
                  <div class="vr_layer">
                    <div class="vr_layer_item"></div>
                  </div>
                  <div class="vr_layer">
                    <div class="vr_layer_item"></div>
                  </div>
                  <div class="vr_layer">
                    <div class="vr_layer_item"></div>
                  </div>
                  <div class="vr_layer">
                    <div class="vr_layer_item"></div>
                  </div>
                  <div class="vr_layer">
                    <div class="vr_layer_item"></div>
                  </div>
                  <div class="vr_layer">
                    <div class="vr_layer_item"></div>
                  </div>
                  <div class="vr_layer">
                    <div class="vr_layer_item"></div>
                  </div>
                  <div class="vr_layer">
                    <div class="vr_layer_item"></div>
                  </div>
                  <div class="vr_layer">
                    <div class="vr_layer_item"></div>
                  </div>
                  <div class="vr_layer">
                    <div class="vr_layer_item"></div>
                  </div>
                  <div class="vr_layer">
                    <div class="vr_layer_item"></div>
                  </div>
                  <div class="vr_layer">
                    <div class="vr_layer_item"></div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Background;
